---
title: 贝克尔的时间分配理论 - 慧航 - 专栏
author: 慧航
date: 2014-09-11
categories: ["6-经济 - 微观计量"]
tags: ["6-慧航", "6-知乎专栏", "6-文献笔记", "6-应用微观计量"]
slug: becker-allocation-of-time
---

**原文地址**：<https://zhuanlan.zhihu.com/p/19847231>

原文：[Gary Beckerís "A Theory of the Allocation of Time"](https://www2.bc.edu/~lewbel/Becker6.pdf)

> Beckerís (1965) paper, "A Theory of the Allocation of Time" revolutionized the modeling of household behavior, by unifying Marshallian demand functions for goods with labor supply and related time use decisions within the household. In this paper we Örst summarize Beckerís time allocation model and associated key contributions, then we show how his original framework extends to modern collective household models.

刚刚去世的经济学巨擘 Becker 因为在家庭、生育、犯罪等领域的开拓性研究而获得诺贝尔奖，并且其影响至今仍然深刻的改变着经济学的研究领域。让我们先对这位前辈致以崇高的敬意和哀悼。

Pierre-André Chiappori 和 Arthur Lewbel 回顾了贝克尔的家庭时间分配的理论。贝克尔通过将家庭生产函数引入到家庭的决策中，提出了一个比较一般性的时间分配的理论框架。作者进而对这一模型的识别问题做了一些综述和评价。

由于贝克尔的这一理论框架是建立在家庭有一个共同的效用函数上的，而最近的理论在 intra-household 的层面上，即家庭内部的层面上，给每个家庭成员设定效用函数来研究家庭的决策问题。其中一个方法是 collective 的方法，即消费品在家庭内部可能是私人消费也可能是公共消费，家庭最终选择一个帕累托最优的组合（其实实证中有的文献做出来发现家庭内部的资源分配不是帕累托最优的）。作者对这一类模型也做了一些简短的综述和评价。

如果对这一块文献感兴趣，可以读一下。