---
title: 正则
date: 2017-06-24
categories: ["6-经济 - 数学与动态"]
tags: ["6-正则点", "6-临界点"]
slug: regular
---

# 临界点、正则点、临界值、正则值

**出处**：经济数学方法与模型, de la Fuente(2000), 朱保华 & 钱晓明(2003), p150-151.

在以后的讨论中，我们需要对函数的雅可比矩阵的秩作出假设，也就是对函数的导数作出假设。特别是，我们可以证明：若函数$f:\mathbb{R}^n\to\mathbb{R}^m$在$x$处可微，且导数矩阵$\mathrm{D}f(x)$的秩为$m$，则$f$的局部行为就可以由$f$的可微性决定。

下面介绍一些在后面将用到的概念。令$f:\mathbb{R}^n\supseteq X\to\mathbb{R}^m$（$X$是开集）是可微函数^[这里的$\mathbb{R}^m$是一个多维的变量，但只要不是集合，就可以认为$f$是函数？]。若$f$在$x\in X$处的微分，即线性映射$\mathrm{d}f_{x}\in L(\mathbb{R}^n,\mathbb{R}^m)$是满射，则称$x$是$f$的正则点（Regular Point）。若$x$不是$f$的正则点，即若$\mathrm{d}f_{x}$不是满射，则称$x$是$f$的临界点（Critical Point）。若$y\in\mathbb{R}^m$是某个临界点的像，则称$y$是$f$的临界值，否则称$y$是$f$的正则值。

可以看到，$\mathrm{d}f_x$是满射，即$x$是$f$的正则点的充要条件是导数$\mathrm{D}f(x)$的秩为$m$。因此，$f:\mathbb{R}^n\supseteq X\to\mathbb{R}^m$的临界点的集合为：

$$
C_f=\left\{\,x\in X;\,\text{rank}\,[\mathrm{D}f(x)]<m\,\right\}
$$

$f$的临界值的集合为$f(C_f)$，正则值的集合为$f(C_f)$的补集，即$\mathbb{R}^m\sim f(C_f)$。可以看到：若$y$不是$X$中任意点的像，根据定义，正则值是那些不是临界值的点，则$y$是$f$的正则值，而$y$是临界值的充要条件是$f^{-1}(y)$至少包含一个临界点，这样$f^{-1}(y)$就不可能是空集。

这个定义将初等微积分中临界点的定义作了推广。若$f$是多元实值函数，我们刚才给出的临界点的定义等价于条件“梯度$\nabla f(x)$是零向量”，因为只有这种情形$\nabla f(x)$不能生成$\mathbb{R}$；若$f$是一元函数，条件为$f'(x)=0$，同样看到：当$f$是从$\mathbb{R}^n$到$\mathbb{R}^n$的函数时，$\mathrm{D}f(x)$是方阵，若$|\mathrm{D}f(x)|=0$，则$x$是临界点。

# 经济是正则的

**出处**：经济学拓扑方法, 王则柯(2001), p305.

设$\pmb{p}$是经济$\varepsilon$的一个均衡价格向量，即$f(\pmb{p})=\pmb{0}$，那么当$\mathrm{Rank}[\mathrm{d}f_{\pmb{p}}]=n-1$时，称均衡价格向量$\pmb{p}$是正则的（Regular）。如果每个均衡价格向量都是正则的，就说该经济$\varepsilon$是正则的^[这里的秩为$n-1$为什么要有一个`-1`，感觉和下面的$\pmb{p}\in\mathbb{S}_+^{n-1}$有关。]。

换言之，如果$f(\pmb{p})=\pmb{0}$时必有$\mathrm{Rank}[\mathrm{d}f_{\pmb{p}}]=n-1$，就说经济$\varepsilon$是正则的。

作为一般经济均衡问题微分方法的初步结果，我们有如下定理^[没有学过拓扑，看不懂。]：

均衡价格向量$\pmb{p}\in\mathbb{S}_+^{n-1}$正则当且仅当在$(\pmb{p},\pmb{0})$，流形$T\mathbb{S}_0^{n-1}$和流形$\text{Graph}\,f$在流形$T^{n-1}$中横截。