baseurl: "https://haopen.github.io/"
languageCode: "en-us"
title: "彭浩 ~ Hao Peng"
theme: "hugo-lithium-theme"
googleAnalytics: ""
disqusShortname: "haopeng"
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 30

permalinks:
  cn: "/cn/:year/:month/:day/:slug/"
  en: "/en/:year/:month/:day/:slug/"
  prof: "/prof/:year/:month/:day/:slug/"
  arts: "/arts/:year/:month/:day/:slug/"
  tech: "/tech/:year/:month/:day/:slug/"

menu:
  main:
    - name: "Blog"
      url: "/en/"
      weight: 1
    - name: "博客"
      url: "/cn/"
      weight: 2
    - name: "人文"
      url: "/arts/"
      weight: 3
    - name: "技术"
      url: "/tech/"
      weight: 4
    - name: "数据"
      url: "/data/"
      weight: 5
    - name: "专业"
      url: "/prof/"
      weight: 6
    - name: "搜索"
      pre: "search"
      url: "#"
      weight: 7
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "About"
      url: "/en/about/"
      weight: 3
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 4
    - name: "中文"
      url: "/cn/"
      weight: 5
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "博客"
      url: "/cn/"
      weight: 2
    - name: "分类"
      url: "/cn/categories/"
      weight: 3
    - name: "关于"
      url: "/cn/about/"
      weight: 4
    - name: "简历"
      url: "/cn/vitae/"
      weight: 5
    - name: "English"
      url: "/en/"
      weight: 6
    - name: "搜索"
      pre: "search"
      url: "#"
      weight: 7
  arts:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "归档"
      url: "/arts/"
      weight: 2
    - name: "分类"
      url: "/arts/categories/"
      weight: 3
    - name: "标签"
      url: "/arts/tags/"
      weight: 4
    - name: "搜索"
      pre: "search"
      url: "#"
      weight: 5
  tech:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "归档"
      url: "/tech/"
      weight: 2
    - name: "分类"
      url: "/tech/categories/"
      weight: 3
    - name: "标签"
      url: "/tech/tags/"
      weight: 4
    - name: "搜索"
      pre: "search"
      url: "#"
      weight: 5
  data:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "归档"
      url: "/data/"
      weight: 2
    - name: "分类"
      url: "/data/categories/"
      weight: 3
    - name: "标签"
      url: "/data/tags/"
      weight: 4
    - name: "搜索"
      pre: "search"
      url: "#"
      weight: 5
  prof:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "归档"
      url: "/prof/"
      weight: 2
    - name: "分类"
      url: "/prof/categories/"
      weight: 3
    - name: "标签"
      url: "/prof/tags/"
      weight: 4
    - name: "搜索"
      pre: "search"
      url: "#"
      weight: 5

outputs:
  home: ["html", "json", "rss"]
  page: ["html"]

params:
  description: "Personal website of Hao Peng; 彭浩的个人网站"
  disqusURL: "https://haopen.github.io/"
  dateFormat: "2005/01/01"
  customCSS: ["css/custom.css", "css/localsearch.css", "lib/lightGallery/css/lightgallery.css"]
  customJS: ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/local-search.js"]
  githubContentURL: "https://github.com/haopen/Blogdown/edit/master/content/"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.11.0"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex", "matlab"]
  highlightjsTheme: "github"

  MathJaxVersion: "2.7.1"
  MathJaxCDN: "//cdn.bootcss.com"

  social:
    twitter: "haopeng"
    weibo: "彭浩"
    weibo_url: "seplost"
    github: "haopen"

  logo:
    url: "logo.png"
    width: 50
    height: 50
    alt: "Hao Peng"

  author:
    en: "Hao Peng"
    cn: "彭浩"

  lang:
    edit:
      en: "Suggest an edit of this page"
      cn: "编辑本页"
      prof: "编辑本页"
      tech: "编辑本页"
      arts: "编辑本页"

  sectionTitle:
    en: "Blog"
    cn: "博客"
    arts: "人文类"
    tech: "技术类"
    data: "数据科学"
    prof: "数学、金融经济类"

  sectionID:
    en: "1-"
    cn: "2-"
    arts: "3-"
    tech: "4-"
    data: "5-"
    prof: "6-"
    1-: "en"
    2-: "cn"
    3-: "arts"
    4-: "tech"
    5-: "data"
    6-: "prof"

  localSearch:
    searchTipsCN: "搜索"
    searchTipsEN: "Search"

blackfriday:
  hrefTargetBlank: true
  # 紧挨着的两行不会被合并成一行，而是变成了 <br />，换行不再需要用 \\
  # 这个选项不开启时，两行虽然可以合并为一行，但有一个空格出现，需要 cjk 修复
  # 但目前 blackfriday 没有这个功能
  extensions: ["hardLineBreak"]
  extensionsmask: ["noIntraEmphasis"]
